//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armys.MusicDal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MusicDatabaseEntities : DbContext
    {
        public MusicDatabaseEntities()
            : base("name=MusicDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sys_arragement> sys_arragement { get; set; }
        public virtual DbSet<sys_authority> sys_authority { get; set; }
        public virtual DbSet<sys_function> sys_function { get; set; }
        public virtual DbSet<sys_usergroup> sys_usergroup { get; set; }
        public virtual DbSet<sys_userinfo> sys_userinfo { get; set; }
        public virtual DbSet<sys_userlog> sys_userlog { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<sys_vw_userinfo> sys_vw_userinfo { get; set; }
    }
}
