//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armys.MusicDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_userinfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sys_userinfo()
        {
            this.sys_arragement = new HashSet<sys_arragement>();
            this.sys_userlog = new HashSet<sys_userlog>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string headportrait { get; set; }
        public bool status { get; set; }
        public Nullable<System.DateTime> datebirth { get; set; }
        public string mobilephone { get; set; }
        public string officephone { get; set; }
        public string qqnumber { get; set; }
        public string homeaddress { get; set; }
        public string personalinformation { get; set; }
        public string remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_arragement> sys_arragement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_userlog> sys_userlog { get; set; }
    }
}
