//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armys.MusicDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_authority
    {
        public int id { get; set; }
        public int usergroup_id { get; set; }
        public int function_id { get; set; }
        public bool display { get; set; }
        public bool edit { get; set; }
        public bool delete { get; set; }
        public bool insert { get; set; }
    
        public virtual sys_function sys_function { get; set; }
        public virtual sys_usergroup sys_usergroup { get; set; }
    }
}
