//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armys.MusicDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_function
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sys_function()
        {
            this.sys_authority = new HashSet<sys_authority>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public int function_id { get; set; }
        public string ico { get; set; }
        public string arrow { get; set; }
        public Nullable<int> sequence { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_authority> sys_authority { get; set; }
    }
}
